import type { Project } from "@/types/project"

export const DEMO_PROJECT_ID = "demo-complidea"

export function createDemoProject(): Project {
  const now = new Date().toISOString()
  return {
    id: DEMO_PROJECT_ID,
    url: "https://complidea.com",
    name: "complidea.com",
    createdAt: now,
    updatedAt: now,
    clone: {
      status: "done",
      progress: 100,
      logs: [
        { timestamp: "2025-01-01T00:00:01.000Z", phase: "fetch", message: "Fetching https://complidea.com...", level: "info" },
        { timestamp: "2025-01-01T00:00:03.000Z", phase: "fetch", message: "Received 48.2 KB of HTML", level: "info" },
        { timestamp: "2025-01-01T00:00:04.000Z", phase: "extract", message: "Extracting site data...", level: "info" },
        { timestamp: "2025-01-01T00:00:05.000Z", phase: "extract", message: "Found: 17 headings, 4 fonts, 20 colors, 12 links", level: "info" },
        { timestamp: "2025-01-01T00:00:06.000Z", phase: "complete", message: "Clone analysis complete", level: "info" },
      ],
      extractedData: {
        title: "Complidea | Şikayetleri Fikre Dönüştürün",
        description: "Reddit'teki kullanıcı problemlerini AI ile analiz ederek uygulama fikirlerine dönüştüren otomasyon sistemi. Gerçek kullanıcı şikayetlerinden SaaS ve MVP fikirleri üretin.",
        fonts: ["Material Symbols Outlined", "sans-serif", "Inter", "-apple-system"],
        colors: [
          "#fbf9f8", "#959aff", "#292b8d", "#30ad43", "#a04100",
          "#006e1f", "#000", "#fff", "#1A202C", "#4FD1C5",
          "#F6AD55", "#FFFFFF", "#E2E8F0", "#2563eb", "#14b8a6",
          "#f3f4f6", "#6b7280", "#1f2937", "#ef4444", "#f59e0b",
        ],
        images: [],
        headings: [
          "Şikayetleri Milyonluk Fikirlere Dönüştürün.",
          "Haftalık Öne Çıkanlar",
          "Etsy Şablon ve Otomasyon",
          "Dijital Dengeleyici",
          "Veri Görselleştirme",
          "Girişimci Kalkanı (Entrepreneur Shield)",
          "Nasıl Çalışıyor?",
          "Problem Tespiti",
          "AI Analizi",
          "Fikir Üretimi",
          "Özellikler",
          "Reddit Entegrasyonu",
          "AI Destekli Analiz",
          "MVP Önerisi",
          "Haftalık Raporlar",
          "Rekabet Analizi",
          "Trend Takibi",
        ],
        links: [
          "https://complidea.com",
          "https://complidea.com/#features",
          "https://complidea.com/#how-it-works",
          "https://complidea.com/#pricing",
        ],
        techStack: ["Next.js", "WordPress", "Tailwind CSS", "Bootstrap", "jQuery", "Google Fonts"],
      },
    },
    analysis: {
      status: "done",
      suggestions: [
        {
          id: "s1",
          category: "ux",
          priority: "high",
          title: "Add loading skeleton states",
          description: "Replace blank loading states with skeleton screens that mirror the layout of actual content, reducing perceived load time.",
          currentState: "Page shows blank areas while content loads",
          suggestedState: "Skeleton placeholders animate during loading",
          effort: "medium",
          applied: false,
        },
        {
          id: "s2",
          category: "performance",
          priority: "high",
          title: "Optimize image loading with lazy loading",
          description: "Add native lazy loading to images below the fold. Use next/image for automatic optimization, WebP conversion, and responsive sizing.",
          currentState: "All images load immediately on page load",
          suggestedState: "Below-fold images load lazily with blur placeholders",
          effort: "easy",
          applied: false,
        },
        {
          id: "s3",
          category: "accessibility",
          priority: "high",
          title: "Improve color contrast ratios",
          description: "Several text-background combinations fail WCAG 2.1 AA contrast requirements. Update colors to meet 4.5:1 ratio for normal text.",
          currentState: "Some text has insufficient contrast (3.2:1 ratio)",
          suggestedState: "All text meets WCAG AA minimum 4.5:1 ratio",
          effort: "easy",
          applied: false,
        },
        {
          id: "s4",
          category: "modern-patterns",
          priority: "medium",
          title: "Implement dark mode support",
          description: "Add system-preference-aware dark mode using CSS custom properties and a toggle switch, improving usability in low-light environments.",
          currentState: "Only light theme available",
          suggestedState: "Dark mode with system preference detection and manual toggle",
          effort: "medium",
          applied: false,
        },
        {
          id: "s5",
          category: "design",
          priority: "medium",
          title: "Modernize card component design",
          description: "Update card components with subtle shadows, hover animations, and consistent border radius for a more polished appearance.",
          currentState: "Flat cards with basic borders",
          suggestedState: "Cards with layered shadows, hover lift effect, and smooth transitions",
          effort: "easy",
          applied: false,
        },
        {
          id: "s6",
          category: "seo",
          priority: "medium",
          title: "Add structured data markup",
          description: "Implement JSON-LD structured data for SoftwareApplication and FAQ schemas to improve search engine rich results.",
          currentState: "No structured data on the page",
          suggestedState: "JSON-LD schemas for product and FAQ content",
          effort: "easy",
          applied: false,
        },
        {
          id: "s7",
          category: "performance",
          priority: "medium",
          title: "Reduce JavaScript bundle size",
          description: "Tree-shake unused imports, code-split routes, and defer non-critical scripts to improve initial page load time.",
          currentState: "Single large JS bundle loaded upfront",
          suggestedState: "Route-based code splitting with deferred loading",
          effort: "hard",
          applied: false,
        },
        {
          id: "s8",
          category: "ux",
          priority: "low",
          title: "Add micro-interactions and transitions",
          description: "Implement subtle animations for buttons, cards, and page transitions to create a more engaging and responsive feel.",
          currentState: "Static UI elements with no animations",
          suggestedState: "Smooth transitions on hover, click, and page navigation",
          effort: "medium",
          applied: false,
        },
      ],
    },
    enhanced: {
      status: "done",
      appliedSuggestionIds: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8"],
    },
  }
}
